export const SET_ACTIVE_SERVER = 'SET_ACTIVE_SERVER';
export const SET_ACTIVE_SERVER_PASSWORD_STATUS =
  'SET_ACTIVE_SERVER_PASSWORD_VALIDITY';

export const FETCH_SERVER_ROLES_RATING = 'FETCH_SERVER_ROLES_RATING';
export const SET_SERVER_RATING_EDIT_DEFAULTS =
  'SET_SERVER_RATING_EDIT_DEFAULTS';

export const SUBMIT_SERVER_ROLES_RATING_EDIT =
  'SUBMIT_SERVER_ROLES_RATING_EDIT';
export const CHECK_SERVER_ROLES_RATING_EDIT_PASSWORD =
  'CHECK_SERVER_ROLES_RATING_EDIT_PASSWORD';
