export const SET_ACTIVE_SERVER = 'SET_ACTIVE_SERVER';

export const FETCH_SERVER_ROLES_RATING = 'FETCH_SERVER_ROLES_RATING';
export const SET_SERVER_TRN_ROLES_RATING = 'SET_SERVER_TRN_ROLES_RATING';

export const FETCH_SERVER_MEMBERS_DONE = 'FETCH_SERVER_MEMBERS_DONE';

export const SUBMIT_SERVER_ROLES_RATING_EDIT =
  'SUBMIT_SERVER_ROLES_RATING_EDIT';
export const CHECK_SERVER_ROLES_RATING_EDIT_PASSWORD =
  'CHECK_SERVER_ROLES_RATING_EDIT_PASSWORD';
